/**
 * Employee Portal API
 * IATec Employee Portal API
 *
 * OpenAPI spec version: 1.0.0-preview-15
 * Contact: andre.guilherme@iatec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Employee {
    code?: string;

    name?: string;

    position?: string;

    document?: models.EmployeeDocument;

    address?: string;

    department?: string;

    isReligious?: boolean;

    admissionDate?: Date;

}
