/**
 * Employee Portal API
 * IATec Employee Portal API
 *
 * OpenAPI spec version: 1.0.0-preview-15
 * Contact: andre.guilherme@iatec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MonthlyReimbursementStatement {
    employee?: models.EmployeeLite;

    entries?: Array<models.MonthlyReimbursementStatementEntry>;

    total?: number;

    internalAccount?: models.InternalAccount;

}
