export * from './PaychecksApi';
import { PaychecksApi } from './PaychecksApi';
export * from './ProfileApi';
import { ProfileApi } from './ProfileApi';
export * from './ReimbursementApi';
import { ReimbursementApi } from './ReimbursementApi';
export * from './ReportsApi';
import { ReportsApi } from './ReportsApi';
export * from './VacationApi';
import { VacationApi } from './VacationApi';
export const APIS = [PaychecksApi, ProfileApi, ReimbursementApi, ReportsApi, VacationApi];
