/**
 * Employee Portal
 * IATec Employee Portal API
 *
 * OpenAPI spec version: 1.0.0-preview-1
 * Contact: andre.guilherme@iatec.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PaycheckApi {

    protected basePath = 'https://virtserver.swaggerhub.com/iatec/Employee/1.0.0-preview-1';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * Get list of available monthly paychecks
     * @summary List monthly paychecks
     * @param kind 
     * @param count The maximum number of items the search will bring.
     * @param maxperiod Limit the search to the specified period of after. The period format is YYYYMM
     */
    public getMonthlyPaycheckListing(kind?: string, count?: number, maxperiod?: number, extraHttpRequestParams?: any): Observable<Array<models.PaycheckListingItem>> {
        return this.getMonthlyPaycheckListingWithHttpInfo(kind, count, maxperiod, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * Get the standard paycheck for a specific period
     * @summary Get paycheck
     * @param kind 
     * @param period 
     * @param includeInternalAccount 
     */
    public getPaycheck(kind: string, period: number, includeInternalAccount?: boolean, extraHttpRequestParams?: any): Observable<models.Paycheck> {
        return this.getPaycheckWithHttpInfo(kind, period, includeInternalAccount, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * List monthly paychecks
     * Get list of available monthly paychecks
     * @param kind 
     * @param count The maximum number of items the search will bring.
     * @param maxperiod Limit the search to the specified period of after. The period format is YYYYMM
     */
    public getMonthlyPaycheckListingWithHttpInfo(kind?: string, count?: number, maxperiod?: number, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/paychecks';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        if (kind !== undefined) {
            queryParameters.set('kind', <any>kind);
        }

        if (count !== undefined) {
            queryParameters.set('count', <any>count);
        }

        if (maxperiod !== undefined) {
            queryParameters.set('maxperiod', <any>maxperiod);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/xml',
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get paycheck
     * Get the standard paycheck for a specific period
     * @param kind 
     * @param period 
     * @param includeInternalAccount 
     */
    public getPaycheckWithHttpInfo(kind: string, period: number, includeInternalAccount?: boolean, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/paychecks/${kind}/${period}'
                    .replace('${' + 'kind' + '}', String(kind))
                    .replace('${' + 'period' + '}', String(period));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'kind' is not null or undefined
        if (kind === null || kind === undefined) {
            throw new Error('Required parameter kind was null or undefined when calling getPaycheck.');
        }
        // verify required parameter 'period' is not null or undefined
        if (period === null || period === undefined) {
            throw new Error('Required parameter period was null or undefined when calling getPaycheck.');
        }
        if (includeInternalAccount !== undefined) {
            queryParameters.set('includeInternalAccount', <any>includeInternalAccount);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/xml',
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
